### ISSUE TITLE
错题26错误

### ISSUE THREAD

**Issue by Big-Aaron** [Devi1k/CUFE901#1]
char str[][8] = {"first","second"},*p = str[0][0];printf("%s\n",p+8);
输出内容为second，每个字符串占8个char

str为二维字符数组，str[0][0]为字符f，应该改为char *p = &str[0][0]; 或者 char *p = str[0];

**Comment by Devi1k** [comment]
谢谢同学的纠正

**Comment by Big-Aaron** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你的邮件我已经收到。

**Comment by Big-Aaron** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你的邮件我已经收到。
